FROM ubuntu

# Labels are used to add metadata to the container

LABEL Maintainer "Rui Grafino"
LABEL Example "5"


# The command CMD, similarly to RUN, can be used for executing a specific command.
# CMD is run only in runtime, not in buidtime

CMD "echo" "Hello World Test!!!"
