FROM ubuntu

# Labels are used to add metadata to the container

LABEL Maintainer "Rui Grafino"
LABEL Example "2"

# Running more than one command and doing a comment

RUN apt-get update && apt-get install -y git
