FROM ubuntu

# Labels are used to add metadata to the container

LABEL Maintainer "Rui Grafino"
LABEL Example "5"

# OR

LABEL Maintainer="Rui Grafino" Example="5"


# The command CMD, similarly to RUN, can be used for executing a specific command.
# CMD is run only in runtime, not in build time.

CMD "echo" "Acess Volume"

# Enable access to a location on the host system from a container.
VOLUME /myvolume
